Algoritmo "CalculaMedia"

Var
notaUm, notaDois, notaTres, notaQuatro, media: real

Inicio
escreva("Digite a Primeira Nota: ")
leia(notaUm)

escreva("Digite a Segunda Nota: ")
leia(notaDois)

escreva("Digite a Terceira Nota: ")
leia(notaTres)

escreva("Digite a Quarta Nota: ")
leia(notaQuatro)

media <- (notaUm + notaDois + notaTres + notaQuatro)/4

escreva("O aluno teve média: ", media)

Fimalgoritmo